fragment BusinessInfo on Business {
  id
  ownerId
  businessName
  businessType {
     id
     name
  }
  businessIndustry
  businessCategory
  businessHours {
    ... BusinessHoursInfo
  }
  activeCheckIns {
    profile {
      avatarUrl
    }
  }
  address
  addressBname
  addressDetails
  addressJibun
  addressSido
  addressSigungu
  addressSigunguCode
  addressSigunguEnglish
  addressZonecode
  bio
  representativeTitle
  representativeName
  phoneNumber
  registrationNumber
  images {
    id
    file {
        url
    }
  }
  lat
  lng
  createdAt
  updatedAt
}
