fragment UserInfo on User {
  id
  email
  status
  role
  profile {
    ... ProfileInfo
  }
  business {
    ... BusinessInfo
  }
  createdAt
  updatedAt
  
  usedLikesCount
  maxLikes
  likesCredit
                    
  loungePassExpiredAt
  invisiblePassExpiredAt
  visibleReactionsPassExpiredAt
  isPhoneNumberVerified
  isEmailVerified
  
  activeCoupons {
    ... ActiveCouponFragment
  }
}

fragment ActiveCouponFragment on ActiveCoupon {
  id
  coupon {
    ... CouponFragment
  }
  expiredAt
}

fragment CouponFragment on Coupon {
  category
  name
  shortDescription
  description
  validFrom
  validUntil
}
